# Generated by Django 4.1.7 on 2023-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=40),
        ),
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='titulo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
