# Generated by Django 4.1.7 on 2023-02-25 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_autor_blog_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fechaPublicacion',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 16, 10, 56, 740636), verbose_name=datetime.datetime(2023, 2, 25, 16, 10, 56, 740636)),
        ),
    ]
