# Generated by Django 4.1.7 on 2023-02-25 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fechaPublicacion',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 21, 13, 49, 679129, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2023, 2, 25, 21, 13, 49, 679129, tzinfo=datetime.timezone.utc)),
        ),
    ]
