# Generated by Django 4.1.7 on 2023-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
