# Generated by Django 4.1.7 on 2023-02-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
