# Generated by Django 4.1.7 on 2023-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_options_remove_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
